### ISSUE TITLE
python error on master

### ISSUE THREAD

**Issue by gioman** [planetfederal/qgis-reports-plugin#1]
works ok on macOS, on Windows

WindowsError: [Error 6] The handle is invalid 
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\reportingtool\plugin.py", line 97, in run
    report, filePath = createReport()
  File "C:\Users\qgis\.qgis2\python\plugins\reportingtool\ext-libs\qgissysinfo\createreport.py", line 49, in createReport
    report = qgissysinfo.info_as_text()
  File "C:\Users\qgis\.qgis2\python\plugins\reportingtool\ext-libs\qgissysinfo\__init__.py", line 31, in info_as_text
    return _as_text(info())
  File "C:\Users\qgis\.qgis2\python\plugins\reportingtool\ext-libs\qgissysinfo\__init__.py", line 8, in info
    _info = systeminfo.allSystemInfo()
  File "C:\Users\qgis\.qgis2\python\plugins\reportingtool\ext-libs\qgissysinfo\systeminfo.py", line 62, in allSystemInfo
    info = systemInfo()
  File "C:\Users\qgis\.qgis2\python\plugins\reportingtool\ext-libs\qgissysinfo\systeminfo.py", line 80, in systemInfo
    "Processor": cpuinfo.get_cpu_info()['brand'],
  File "C:\Users\qgis\.qgis2\python\plugins\reportingtool\ext-libs\cpuinfo\cpuinfo.py", line 1787, in get_cpu_info
    CopyNewFields(info, _get_cpu_info_from_cpuid())
  File "C:\Users\qgis\.qgis2\python\plugins\reportingtool\ext-libs\cpuinfo\cpuinfo.py", line 1121, in _get_cpu_info_from_cpuid
    returncode, output = run_and_get_stdout([sys.executable, "-c", "import cpuinfo; print(cpuinfo.actual_get_cpu_info_from_cpuid())"])
  File "C:\Users\qgis\.qgis2\python\plugins\reportingtool\ext-libs\cpuinfo\cpuinfo.py", line 203, in run_and_get_stdout
    p1 = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.0\osgeo4w\apps\Python27\lib\subprocess.py", line 703, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.0\osgeo4w\apps\Python27\lib\subprocess.py", line 839, in _get_handles
    p2cread = self._make_inheritable(p2cread)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.0\osgeo4w\apps\Python27\lib\subprocess.py", line 878, in _make_inheritable
    _subprocess.DUPLICATE_SAME_ACCESS)
WindowsError: [Error 6] The handle is invalid

**Comment by alexbruy** [comment]
Should be fixed
