### ISSUE TITLE
Python error while trying to use the support tool menu item

### ISSUE THREAD

**Issue by SrNetoChan** [planetfederal/qgis-reports-plugin#2]
This happens in a Windows 10 VM, with Boundless Desktop 1.1 RC_6.

some particularities of the VM that may be causing this:
- Date time is set to Lisbon time
- Keyboard is set to Portuguese

No other changes were made.

```
An error has occurred while executing Python code: 

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 10: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python/plugins\reportingtool\plugin.py", line 111, in run
    report, filePath = createReport()
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\ext-libs\qgissysinfo\createreport.py", line 49, in createReport
    report = qgissysinfo.info_as_text()
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\ext-libs\qgissysinfo\__init__.py", line 31, in info_as_text
    return _as_text(info())
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\ext-libs\qgissysinfo\__init__.py", line 8, in info
    _info = systeminfo.allSystemInfo()
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\ext-libs\qgissysinfo\systeminfo.py", line 63, in allSystemInfo
    info.update(pythonInfo())
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\ext-libs\qgissysinfo\systeminfo.py", line 95, in pythonInfo
    from pip.operations.freeze import freeze
  File "C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\__init__.py", line 26, in 
    from pip.utils import get_installed_distributions, get_prog
  File "C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\utils\__init__.py", line 27, in 
    from pip._vendor import pkg_resources
  File "C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3018, in 
    @_call_aside
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3031, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 651, in _build_master
    ws = cls()
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2010, in find_on_path
    path_item_entries = _by_version_descending(os.listdir(path_item))
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1994, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1992, in _by_version
    return [packaging.version.parse(part) for part in parts]
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\packaging\version.py", line 31, in parse
    return Version(version)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\pip\_vendor\packaging\version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 10: ordinal not in range(128)


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.10 Las Palmas, 650ca524eb 

Python Path:
C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python/plugins\processing
C:\Users\boundless\.qgis2\python\plugins\webappbuilder\ext-libs\future-0.16.0-py2.7.egg
C:\Users\boundless\.qgis2\python\plugins\webappbuilder\ext-libs\requests-2.18.1-py2.7.egg
C:\Users\boundless\.qgis2\python\plugins\webappbuilder\ext-libs\certifi-2017.4.17-py2.7.egg
C:\Users\boundless\.qgis2\python\plugins\webappbuilder\ext-libs\urllib3-1.21.1-py2.7.egg
C:\Users\boundless\.qgis2\python\plugins\webappbuilder\ext-libs\idna-2.5-py2.7.egg
C:\Users\boundless\.qgis2\python\plugins\webappbuilder\ext-libs\chardet-3.0.4-py2.7.egg
C:\Users\boundless\.qgis2\python\plugins\webappbuilder\ext-libs\PyPubSub-3.3.0-py2.7.egg
C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python
C:/Users/boundless/.qgis2/python
C:/Users/boundless/.qgis2/python/plugins
C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python/plugins
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\bin\python27.zip
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\DLLs
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\plat-win
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\lib-tk
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\bin
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/boundless/.qgis2//python
C:\Users\boundless\.qgis2\python\plugins\webappbuilder\ext-libs
C:/Users/boundless/.qgis2/python/plugins\webappbuilder
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\boundlessconnect\ext-libs
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\boundlessconnect\ext-libs\future-0.16.0-py2.7.egg
C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\ext-libs
C:/Users/boundless/.qgis2/python/plugins/webappbuilder/tests/data
```

Using the console It worked, an dI got this report:

```
-Python information
	-Python version
		-2.7.5 ('default', 'May 15 2013 22:44:16')
	-Python implementation
		-CPython
	-Exec prefix
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27
	-Python binary path
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\bin\python.exe
	-Prefix
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27
	-pip freeze
		-alabaster==0.7.10
		-Babel==2.4.0
		-backports-abc==0.5
		-backports.shutil-get-terminal-size==1.0.0
		-backports.ssl-match-hostname==3.5.0.1
		-bleach==2.0.0
		-certifi==2017.4.17
		-colorama==0.3.9
		-configparser==3.5.0
		-cycler==0.10.0
		-decorator==4.0.11
		-docutils==0.13.1
		-entrypoints==0.2.3
		-enum34==1.1.6
		-funcsigs==0.4
		-functools32==3.2.3.post2
		-future==0.15.2
		-GDAL==2.2.0
		-html5lib==0.999999999
		-httplib2==0.9.2
		-imagesize==0.7.1
		-ipykernel==4.6.1
		-ipython==5.4.1
		-ipython-genutils==0.2.0
		-ipywidgets==6.0.0
		-jinja2==2.7.2
		-jsonschema==2.6.0
		-jupyter==1.0.0
		-jupyter-client==5.0.1
		-jupyter-console==5.1.0
		-jupyter-core==4.3.0
		-markupsafe==0.23
		-matplotlib==2.0.0
		-mistune==0.7.4
		-mock==1.3.0
		-nbconvert==5.2.1
		-nbformat==4.3.0
		-nose==1.3.7
		-nose2==0.6.4
		-notebook==5.0.0
		-numpy==1.12.1+mkl
		-olefile==0.44
		-OWSLib==0.14.0
		-pandocfilters==1.4.1
		-pathlib2==2.3.0
		-Paver==1.2.4
		-pbr==1.8.1
		-pickleshare==0.7.4
		-Pillow==4.1.0
		-pip==9.0.1
		-prompt-toolkit==1.0.14
		-psutil==5.2.2
		-psycopg2==2.5.1
		-py-cpuinfo==3.3.0
		-Pygments==2.2.0
		-PyOpenGL==3.0.1
		-pyparsing==2.2.0
		-pyproj==1.9.5.1
		-python-dateutil==2.6.0
		-pytz==2017.2
		-pywin32==218
		-PyYAML==3.12
		-pyzmq==16.0.2
		-qgissysteminfo==0.1.0
		-qtconsole==4.3.0
		-requests==2.13.0
		-scandir==1.5
		-scipy==0.19.0
		-setuptools==36.0.1
		-shapely==1.2.18
		-simplegeneric==0.8.1
		-simplejson==3.3.0
		-singledispatch==3.4.0.3
		-six==1.10.0
		-snowballstemmer==1.2.1
		-Sphinx==1.6.2
		-sphinxcontrib-restbuilder==0.1
		-sphinxcontrib-websupport==1.0.1
		-testpath==0.3.1
		-tornado==4.5.1
		-traitlets==4.3.2
		-typing==3.6.1
		-wcwidth==0.1.7
		-webencodings==0.5.1
		-widgetsnbextension==2.0.0
		-win-unicode-console==0.5
		-xlrd==0.9.2
		-xlwt==0.7.5
	-Module search paths
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\ext-libs\qgissysinfo
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python
		-C:\Users\boundless\"C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\ext-libs\qgissysinfo"
		-C:\Users\boundless
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\bin\python27.zip
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\DLLs
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\plat-win
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\lib-tk
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\bin
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\win32
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\win32\lib
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\Pythonwin
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
		-C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\qgis\python\plugins\reportingtool\ext-libs
-QGIS providers
	-Available QGIS data provider plugins
		-DB2 Spatial Extender provider
		-WFS data provider
		-ArcGIS Feature Server data provider
		-ArcGIS Map Server data provider
		-Delimited text data provider
		-GDAL provider
		-GPS eXchange format provider
		-Memory provider
		-MSSQL spatial data provider
		-OGR data provider (compiled against GDAL/OGR library version 2.2.0, running against GDAL/OGR library version 2.2.0)
		-Oracle data provider
		-OWS meta provider
		-PostgreSQL/PostGIS data provider
		-SpatiaLite data provider
		-Virtual layer data provider
		-OGC Web Coverage Service version 1.0/1.1 data provider
		-OGC Web Map Service version 1.3 data provider
		-
-QGIS authentication methods
	-Available QGIS authentication plugins
		-PKI-Paths: PKI paths authentication
		-PKI-PKCS#12: PKI PKCS#12 authentication
		-Basic: Basic authentication
		-Identity-Cert: PKI stored identity certificate
		-OAuth2: OAuth2 authentication
-Qt/PyQt information
	-Qt version
		-4.8.5
	-Qt image plugins
		-bmp
		-gif
		-ico
		-jpeg
		-jpg
		-mng
		-pbm
		-pgm
		-png
		-ppm
		-svg
		-svgz
		-tga
		-tif
		-tiff
		-xbm
		-xpm
	-Qt library paths
		-C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/qtplugins
		-C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qt4/plugins
	-Qt database plugins
		-QPSQL7
		-QPSQL
		-QODBC3
		-QODBC
		-QOCISPATIAL8
		-QOCISPATIAL
		-QSPATIALITE
		-QSQLITE
		-QMYSQL3
		-QMYSQL
		-QOCI8
		-QOCI
	-PyQt version
		-4.10.2
	-SIP version
		-4.14.7
-QGIS plugins
	-Active C++ plugins
		-keychainbridgeplugin
	-Available Python plugins
		-boundlessconnect (1.0.0) in C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/.\python\plugins\boundlessconnect
		-db_manager (0.1.20) in C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/.\python\plugins\db_manager
		-GdalTools (1.2.29) in C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/.\python\plugins\GdalTools
		-MetaSearch (0.3.5) in C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/.\python\plugins\MetaSearch
		-processing (2.12.99) in C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/.\python\plugins\processing
		-reportingtool (1.0) in C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/.\python\plugins\reportingtool
		-qgistester (0.1-201701020817-de65150) in C:/Users/boundless/.qgis2\python\plugins\qgistester
		-webappbuilder (0.99-201706281110-ee97605) in C:/Users/boundless/.qgis2\python\plugins\webappbuilder
	-Active Python plugins
		-GdalTools
		-MetaSearch
		-boundlessconnect
		-db_manager
		-processing
		-qgistester
		-reportingtool
		-webappbuilder
-QGIS settings
	-Plugin repositories
		-Boundless DEV: https://qgis-dev.boundlessgeo.com/plugins/plugins.xml (enabled, no auth)
		-Boundless Plugin Repository: https://qgis.boundlessgeo.com/plugins.xml (enabled, need auth)
		-QGIS Official Plugin Repository: https://plugins.qgis.org/plugins/plugins.xml (enabled, no auth)
-QGIS information
	-QGIS prefix path
		-C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis
	-QGIS library path
		-C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/lib/
	-QGIS pkg data path
		-C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/.
	-QGIS lib exec path
		-C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./
	-QGIS version
		-2.18.10 (650ca524eb)
	-QGIS application state
		-QGIS_PREFIX_PATH env var: C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis
		-Prefix: C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis
		-Plugin Path: C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/plugins
		-Package Data Path:	C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/.
		-Active Theme Name:	
		-Active Theme Path:	C:/Users/boundless/.qgis2///themes\\icons/
		-Default Theme Path:	:/images/themes/default/
		-SVG Search Paths:	C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./svg/
		- C:/Users/boundless/.qgis2//svg/
		-User DB Path:	C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./resources/qgis.db
		-Auth DB Path:	C:/Users/boundless/.qgis2//qgis-auth.db
		-
-System information
	-CPU cores
		-2 (total), 2 (physical)
	-Operating system
		-Windows-8-6.2.9200
	-Installed RAM
		-2.4 G
	-Hostname
		-DESKTOP-1D327CJ
	-User name
		-boundless
	-Home directory
		-C:\Users\boundless
	-Processor
		-Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
```

**Comment by gioman** [comment]
I wasn't able to replicate after the same changes.

**Comment by alexbruy** [comment]
I also can't reproduce.

**Comment by gioman** [comment]
@SrNetoChan please reopen if you find a consistent way to get this error.
