### ISSUE TITLE
AttributeError: 'ModuleNotFoundError' object has no attribute 'output'

### ISSUE THREAD

**Issue by SrNetoChan** [planetfederal/qgis-reports-plugin#5]
Got this error trying to use the plugin on QGIS 3 master on windows.

```
An error has occurred while executing Python code: 

AttributeError: 'ModuleNotFoundError' object has no attribute 'output' 
Traceback (most recent call last):
  File "C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs\qgissysteminfo-0.1.0-py3.6.egg\qgissysinfo\systeminfo.py", line 96, in pythonInfo
    from pip.operations.freeze import freeze
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 671, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/boundless/AppData/Roaming/QGIS/QGIS3\profiles\teste/python/plugins\reportingtool\plugin.py", line 109, in run
    report, filePath = createReport()
  File "C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs\qgissysteminfo-0.1.0-py3.6.egg\qgissysinfo\createreport.py", line 49, in createReport
    report = qgissysinfo.info_as_text()
  File "C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs\qgissysteminfo-0.1.0-py3.6.egg\qgissysinfo\__init__.py", line 31, in info_as_text
    return _as_text(info())
  File "C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs\qgissysteminfo-0.1.0-py3.6.egg\qgissysinfo\__init__.py", line 8, in info
    _info = systeminfo.allSystemInfo()
  File "C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs\qgissysteminfo-0.1.0-py3.6.egg\qgissysinfo\systeminfo.py", line 64, in allSystemInfo
    info.update(pythonInfo())
  File "C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs\qgissysteminfo-0.1.0-py3.6.egg\qgissysinfo\systeminfo.py", line 101, in pythonInfo
    pipInfo = ["Could not get PIP information: {}".format(e.output)]
AttributeError: 'ModuleNotFoundError' object has no attribute 'output'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.3.0-Master Master, 2fce5700e4 

Python Path:
C:/OSGEO4~1/apps/qgis-dev/./python
C:/Users/boundless/AppData/Roaming/QGIS/QGIS3\profiles\teste/python
C:/Users/boundless/AppData/Roaming/QGIS/QGIS3\profiles\teste/python/plugins
C:/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/boundless/AppData/Roaming/QGIS/QGIS3\profiles\teste/python
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\lessons\extlibs
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\lessons\extlibs\future-0.16.0-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\lessons\extlibs\Markdown-3.0.1-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\lessons\extlibs\qgiscommons-2.0.12-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs\qgissysteminfo-0.1.0-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs\py_cpuinfo-4.0.0-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\reportingtool\extlibs\psutil-5.4.7-py3.6-linux-x86_64.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\plotly-2.5.1-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\six-1.11.0-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\requests-2.19.1-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\urllib3-1.23-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\idna-2.7-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\chardet-3.0.4-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\certifi-2018.8.24-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\pytz-2018.5-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\nbformat-4.4.0-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\traitlets-4.3.2-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\ipython_genutils-0.2.0-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\decorator-4.1.2-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\jupyter_core-4.4.0-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\jsonschema-2.6.0-py3.6.egg
C:\Users\boundless\AppData\Roaming\QGIS\QGIS3\profiles\teste\python\plugins\terrainanalysis\extlibs\qgiscommons-2.0.12-py3.6.egg
```

**Comment by volaya** [comment]
fixed in qgissysinfo library 

you will need to run paver setup to get those changes
